### ISSUE TITLE
can not upload file 

### ISSUE THREAD

**Issue by zzduci** [freelamb/simple_http_server#18]
~ $ cd simple_http_server
~/simple_http_server $ python simple_http_server.py 8000
server_version: simple_http_server/0.3.1, python_version: Python/3.11.3
sys encoding: utf-8
Serving http on: 0.0.0.0, port: 8000 ... (http://0.0.0.0:8000/)
10.0.0.149 - - [29/May/2023 11:22:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/May/2023 11:22:14] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 45442)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.11/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/data/data/com.termux/files/usr/lib/python3.11/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/data/data/com.termux/files/usr/lib/python3.11/http/server.py", line 420, in handle_one_request
    method()
  File "/data/data/com.termux/files/home/simple_http_server/simple_http_server.py", line 59, in do_GET
    shutil.copyfileobj(fd, self.wfile)
  File "/data/data/com.termux/files/usr/lib/python3.11/shutil.py", line 200, in copyfileobj
    fdst_write(buf)
  File "/data/data/com.termux/files/usr/lib/python3.11/socketserver.py", line 834, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------

**Comment by zzduci** [comment]
Upload Result Page
Success:File '/data/data/com.termux/files/home/simple_http_server/李跳跳·派大星 v2.2.0_2.apk' upload success!
[back](http://10.0.0.146:8000/)
Powered By: freelamb, check new version at [here](https://github.com/freelamb/simple_http_server).  




sorry ,it is OK now

**Comment by freelamb** [comment]
get
